import { Component } from '@angular/core';
import { Album } from '../../components/gallery/album';
import { GalleryComponent } from '../../components/gallery/gallery.component';

@Component({
  selector: 'app-north-america',
  imports: [GalleryComponent],
  templateUrl: './north-america.component.html',
})
export class NorthAmericaComponent {
  albums: Album[] = [
    {
      label: 'Canada',
      icons: ['canada'],
      urls: [
        'photos/north-america/canada-1.jpg',
        'photos/north-america/canada-2.jpg',
        'photos/north-america/canada-3.jpg',
        'photos/north-america/canada-4.jpg',
        'photos/north-america/canada-5.jpg',
        'photos/north-america/canada-6.jpg',
        'photos/north-america/canada-7.jpg',
        'photos/north-america/canada-8.jpg',
        'photos/north-america/canada-9.jpg',
        'photos/north-america/canada-10.jpg',
        'photos/north-america/canada-11.jpg',
        'photos/north-america/canada-12.jpg',
        'photos/north-america/canada-13.jpg',
        'photos/north-america/canada-14.jpg',
        'photos/north-america/canada-15.jpg',
        'photos/north-america/canada-16.jpg',
        'photos/north-america/canada-17.jpg',
        'photos/north-america/canada-18.jpg',
        'photos/north-america/canada-19.jpg',
        'photos/north-america/canada-20.jpg',
        'photos/north-america/canada-21.jpg',
        'photos/north-america/canada-22.jpg',
        'photos/north-america/canada-23.jpg',
      ],
    },
    {
      label: 'Guatemala & Costa Rica',
      icons: ['guatemala', 'costa-rica'],
      urls: [
        'photos/north-america/guatemala-costa-rica-1.jpg',
        'photos/north-america/guatemala-costa-rica-2.jpg',
        'photos/north-america/guatemala-costa-rica-3.jpg',
        'photos/north-america/guatemala-costa-rica-4.jpg',
        'photos/north-america/guatemala-costa-rica-5.jpg',
        'photos/north-america/guatemala-costa-rica-6.jpg',
      ],
    },
    {
      label: 'Mexico',
      icons: ['mexico'],
      urls: [
        'photos/north-america/mexico-1.jpg',
        'photos/north-america/mexico-2.jpg',
        'photos/north-america/mexico-3.jpg',
        'photos/north-america/mexico-4.jpg',
        'photos/north-america/mexico-5.jpg',
        'photos/north-america/mexico-6.jpg',
        'photos/north-america/mexico-7.jpg',
        'photos/north-america/mexico-8.jpg',
        'photos/north-america/mexico-9.jpg',
        'photos/north-america/mexico-10.jpg',
        'photos/north-america/mexico-11.jpg',
        'photos/north-america/mexico-12.jpg',
      ],
    },
    {
      label: 'United States',
      icons: ['usa'],
      urls: [
        'photos/north-america/usa-1.jpg',
        'photos/north-america/usa-2.jpg',
        'photos/north-america/usa-3.jpg',
        'photos/north-america/usa-4.jpg',
        'photos/north-america/usa-5.jpg',
        'photos/north-america/usa-6.jpg',
        'photos/north-america/usa-7.jpg',
        'photos/north-america/usa-8.jpg',
        'photos/north-america/usa-9.jpg',
        'photos/north-america/usa-10.jpg',
        'photos/north-america/usa-11.jpg',
        'photos/north-america/usa-12.jpg',
        'photos/north-america/usa-13.jpg',
        'photos/north-america/usa-14.jpg',
        'photos/north-america/usa-15.jpg',
        'photos/north-america/usa-16.jpg',
        'photos/north-america/usa-17.jpg',
        'photos/north-america/usa-18.jpg',
        'photos/north-america/usa-19.jpg',
        'photos/north-america/usa-20.jpg',
        'photos/north-america/usa-21.jpg',
        'photos/north-america/usa-22.jpg',
        'photos/north-america/usa-23.jpg',
        'photos/north-america/usa-24.jpg',
        'photos/north-america/usa-25.jpg',
        'photos/north-america/usa-26.jpg',
        'photos/north-america/usa-27.jpg',
        'photos/north-america/usa-28.jpg',
        'photos/north-america/usa-29.jpg',
        'photos/north-america/usa-30.jpg',
        'photos/north-america/usa-31.jpg',
        'photos/north-america/usa-32.jpg',
        'photos/north-america/usa-33.jpg',
        'photos/north-america/usa-34.jpg',
        'photos/north-america/usa-35.jpg',
        'photos/north-america/usa-36.jpg',
        'photos/north-america/usa-37.jpg',
        'photos/north-america/usa-38.jpg',
      ],
    },
  ];
}
