import { Component } from '@angular/core';
import { PhotoAlbum } from '../../components/photo-library/photo-album';
import { PhotoLibraryComponent } from '../../components/photo-library/photo-library.component';

@Component({
  selector: 'app-north-america',
  imports: [PhotoLibraryComponent],
  templateUrl: './north-america.component.html',
})
export class NorthAmericaComponent {
  albums: PhotoAlbum[] = [
    {
      label: 'Canada',
      icons: ['canada'],
      urls: [
        'photos/north-america/canada-1.jpg',
        'photos/north-america/canada-2.jpg',
        'photos/north-america/canada-3.jpg',
        'photos/north-america/canada-4.jpg',
        'photos/north-america/canada-5.jpg',
        'photos/north-america/canada-6.jpg',
        'photos/north-america/canada-7.jpg',
        'photos/north-america/canada-8.jpg',
        'photos/north-america/canada-9.jpg',
        'photos/north-america/canada-10.jpg',
        'photos/north-america/canada-11.jpg',
        'photos/north-america/canada-12.jpg',
        'photos/north-america/canada-13.jpg',
        'photos/north-america/canada-14.jpg',
        'photos/north-america/canada-15.jpg',
        'photos/north-america/canada-16.jpg',
        'photos/north-america/canada-17.jpg',
        'photos/north-america/canada-18.jpg',
        'photos/north-america/canada-19.jpg',
        'photos/north-america/canada-20.jpg',
        'photos/north-america/canada-21.jpg',
        'photos/north-america/canada-22.jpg',
        'photos/north-america/canada-23.jpg',
      ],
    },
    {
      label: 'Guatemala & Costa Rica',
      icons: ['guatemala', 'costa rica'],
      urls: [
        'photos/north-america/guatemala-costa-rica-1.jpg',
        'photos/north-america/guatemala-costa-rica-2.jpg',
        'photos/north-america/guatemala-costa-rica-3.jpg',
        'photos/north-america/guatemala-costa-rica-4.jpg',
        'photos/north-america/guatemala-costa-rica-5.jpg',
        'photos/north-america/guatemala-costa-rica-6.jpg',
      ],
    },
    {
      label: 'Mexico',
      icons: ['mexico'],
      urls: [
        'photos/north-america/mexico-1.jpg',
        'photos/north-america/mexico-2.jpg',
        'photos/north-america/mexico-3.jpg',
        'photos/north-america/mexico-4.jpg',
        'photos/north-america/mexico-5.jpg',
        'photos/north-america/mexico-6.jpg',
        'photos/north-america/mexico-7.jpg',
        'photos/north-america/mexico-8.jpg',
        'photos/north-america/mexico-9.jpg',
        'photos/north-america/mexico-10.jpg',
        'photos/north-america/mexico-11.jpg',
        'photos/north-america/mexico-12.jpg',
      ],
    },
    {
      label: 'United States',
      icons: ['usa'],
      urls: [
        'photos/north-america/usa-1.jpg',
        'photos/north-america/usa-2.jpg',
        'photos/north-america/usa-3.jpg',
        'photos/north-america/usa-4.jpg',
        'photos/north-america/usa-5.jpg',
        'photos/north-america/usa-6.jpg',
        'photos/north-america/usa-7.jpg',
        'photos/north-america/usa-8.jpg',
        'photos/north-america/usa-9.jpg',
        'photos/north-america/usa-10.jpg',
        'photos/north-america/usa-11.jpg',
        'photos/north-america/usa-12.jpg',
        'photos/north-america/usa-13.jpg',
        'photos/north-america/usa-14.jpg',
        'photos/north-america/usa-15.jpg',
        'photos/north-america/usa-16.jpg',
        'photos/north-america/usa-17.jpg',
        'photos/north-america/usa-18.jpg',
        'photos/north-america/usa-19.jpg',
        'photos/north-america/asa-20.jpg',
        'photos/north-america/asa-21.jpg',
        'photos/north-america/asa-22.jpg',
        'photos/north-america/asa-23.jpg',
        'photos/north-america/asa-24.jpg',
        'photos/north-america/asa-25.jpg',
        'photos/north-america/asa-26.jpg',
        'photos/north-america/asa-27.jpg',
        'photos/north-america/asa-28.jpg',
        'photos/north-america/asa-29.jpg',
        'photos/north-america/asa-30.jpg',
        'photos/north-america/asa-31.jpg',
        'photos/north-america/asa-32.jpg',
        'photos/north-america/asa-33.jpg',
        'photos/north-america/asa-34.jpg',
        'photos/north-america/asa-35.jpg',
        'photos/north-america/asa-36.jpg',
        'photos/north-america/asa-37.jpg',
        'photos/north-america/asa-38.jpg',
      ],
    },
  ];
}
