name: Deploy Angular Project to GitHub Pages
'on':
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: Replace Variables
        run: |
          sed -i 's/${FIREBASE_API_KEY}/'${{ secrets.FIREBASE_API_KEY }}'/g' src/environments/environment.prod.ts
          sed -i 's/${FIREBASE_AUTH_DOMAIN}/'${{ secrets.FIREBASE_AUTH_DOMAIN }}'/g' src/environments/environment.prod.ts
          sed -i 's/${FIREBASE_PROJECT_ID}/'${{ secrets.FIREBASE_PROJECT_ID }}'/g' src/environments/environment.prod.ts
          sed -i 's/${FIREBASE_STORAGE_BUCKET}/'${{ secrets.FIREBASE_STORAGE_BUCKET }}'/g' src/environments/environment.prod.ts
          sed -i 's/${FIREBASE_MESSAGING_SENDER_ID}/'${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'/g' src/environments/environment.prod.ts
          sed -i 's/${FIREBASE_APP_ID}/'${{ secrets.FIREBASE_APP_ID }}'/g' src/environments/environment.prod.ts

      - name: Build the project
        run: npm run .1
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: ./docs
